### ISSUE TITLE
Graph algorithms? 

### ISSUE THREAD

**Issue by anicolaspp** [Verizon/quiver#14]
I have special interest on building and working with functional graphs. If this the right place to add graph algorithms? Will you guys accept PRs with those? or should I create my own project that uses this lib?

**Comment by runarorama** [comment]
Absolutely, this project already includes some simple graph algorithms. See e.g. shortest path: https://github.com/Verizon/quiver/blob/master/core/src/main/scala/Graph.scala#L865

Check whether FGL already includes what you need, and we can just port that: https://hackage.haskell.org/package/fgl

**Comment by anicolaspp** [comment]
I have interest on subtracting the articulation points and doing topological sorts. I can submit a PR with those.

**Comment by runarorama** [comment]
Please do
