### ISSUE TITLE
Port Quiver to Cats

### ISSUE THREAD

**Issue by joroKr21** [Verizon/quiver#19]
[typelevel/cats](https://github.com/typelevel/cats) is an alternative to Scalaz for functional programming in Scala.

It would be nice to port Quiver and create a version based on Cats for projects that would like to avoid a dependency on Scalaz. It would be even better to factor out functionality related to Cats or Scalaz in separate modules, e.g. `quiver-cats` and `quiver-scalaz`.

As far as I can tell Scalaz is used only for `scalaz.Tree` and to define type class instances for nodes, edges, graphs, etc. ATM the only missing piece of functionality in Cats is `Tree`.

**Comment by rossabaker** [comment]
Yes, I am interested in this port.  I'm going to start looking into this.
